### ISSUE TITLE
should these eigenvecs differ this much?

### ISSUE THREAD

**Issue by JeffreySarnoff** [RalphAS/GenericSchur.jl#1]
```julia
julia> using GenericSchur, LinearAlgebra

julia> setprecision(BigFloat,53)
53

julia> m = reshape([1.0, 12.0, 8.0, 5.0],2,2)
2×2 Array{Float64,2}:
  1.0  8.0
 12.0  5.0

julia> b=BigFloat.(m)
2×2 Array{BigFloat,2}:
  1.0  8.0
 12.0  5.0

julia> eigen(m)
Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}
eigenvalues:
2-element Array{Float64,1}:
 -7.0
 13.0
eigenvectors:
2×2 Array{Float64,2}:
 -0.707107  -0.5547
  0.707107  -0.83205

julia> eigen(b)
Eigen{Complex{BigFloat},Complex{BigFloat},Array{Complex{BigFloat},2},Array{Complex{BigFloat},1}}
eigenvalues:
2-element Array{Complex{BigFloat},1}:
 -7.0 + 0.0im
 13.0 + 0.0im
eigenvectors:
2×2 Array{Complex{BigFloat},2}:
 -1.0+0.0im  0.666667+0.0im
  1.0+0.0im       1.0+0.0im
```

**Comment by RalphAS** [comment]
In principle there is an arbitrary scale factor for eigenvectors, and the LinearAlgebra developers didn't document the selection criterion, but consistency would be preferable.
I should have followed the LAPACK convention for normalization (unit Euclidean norm), since that is inherited by Julia for BLAS types. I'll plan on doing that in an upcoming release.
Note that an ambiguity of phase factor will likely perdure.
Thanks for bringing it to my attention.

**Comment by kagalenko-m-b** [comment]
Not normalizing eigenvectors results in breakdown of the relation
```
E,Q = svd(A)
A \approx E*Q*E'
```

It is a serious bug.

**Comment by RalphAS** [comment]
Can you clarify? I'm not aware of a version of `svd` which would invoke methods in this package.
But
```julia
E,Q = eigen(A)
A \approx Q*Diagonal(E)*inv(Q)
```
should work with the existing (lack of) normalization, as long as `Q` is reasonably well-conditioned.

(I don't mean to be dismissive; I do intend to standardize the normalization.)

**Comment by kagalenko-m-b** [comment]
Sorry, svd() was a typo. 

Note, that in your version you use inv(Q), because the Q is not orthogonal.

**Comment by JeffreySarnoff** [comment]
Leading with ignorance and hoping to provide a coherent way forward ...
Here is an answer to [how matlab normalizes eigenvectors](https://www.mathworks.com/matlabcentral/answers/385968-how-does-matlabs-eigs-normalise-eigenvectors).

**Comment by kagalenko-m-b** [comment]
Matlab relies on LAPACK for most of its linear algebra, so it is not surprising that it normalizes the eigenvectors the same way. So does scipy/numpy.

**Comment by JeffreySarnoff** [comment]
Normalize usually implies `to unity` for this class of numerical algorithms.

**Comment by kagalenko-m-b** [comment]
And that's what Matlab's eig() does. In case of **generalized** eigenvalue problem it uses non-euclidean norm.

**Comment by JeffreySarnoff** [comment]
can you make a PR to help resolve this?

**Comment by kagalenko-m-b** [comment]
I am insufficiently familiar with GenericSchur internals, sorry. In my own program I just normalize them myself
```
for k = 1:size(Q)[2]
  Q[:, k] /= norm(Q[:, k])
end
```

**Comment by RalphAS** [comment]
The requested normalization convention is in v0.4.0, and is now documented and tested.

**Comment by JeffreySarnoff** [comment]
(thanks Ralph -- `its a hit, a long ball .. and the crowd goes wild!`)

**Comment by kagalenko-m-b** [comment]
Thank you, Ralph, that is very helpful!
